version: "3.8"

volumes:
    devops_redis:
    devops_postgres:

services:
    app:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: dev
            args:
                user: ${DOCKER_DEFAULT_USER:-devops}
                uid: ${DOCKER_DEFAULT_UID:-1000}
        volumes:
            - ./:/usr/src/
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        extra_hosts:
            - "host.docker.internal:host-gateway"

    redis:
        image: redis:7.2.4-alpine
        restart: unless-stopped
        volumes:
            - devops_redis:/data
        ports:
            - "63790:6379"
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            PGUSER: ${DB_USERNAME:-postgres}
            POSTGRES_DB: ${DB_DATABASE:-devops}
        volumes:
            - devops_postgres:/var/lib/postgresql/data
            - ./deployment/config/postgres/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
        ports:
            - "54320:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:1.26.0-alpine
        restart: unless-stopped
        volumes:
            - ./:/usr/src
            - ./deployment/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            app:
                condition: service_started

    frontend:
        restart: unless-stopped
        tty: true
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
            target: dev
        volumes:
            - ./:/usr/src/
        ports:
            - "5173:5173"
        depends_on:
            app:
                condition: service_started
