volumes:
    devops_redis:
    devops_postgres:

services:
    app:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile.php
            target: prod
            args:
                user: ${DOCKER_DEFAULT_USER:-devops}
                uid: ${DOCKER_DEFAULT_UID:-1000}
        volumes:
            - ./app:/usr/src/app
            - ./config:/usr/src/config
            - ./database:/usr/src/database
            - ./resources:/usr/src/resources
            - ./routes:/usr/src/routes
            - ./storage:/usr/src/storage
            - ./tests:/usr/src/tests
            - ./.env:/usr/src/.env
            - ./composer.json:/usr/src/composer.json
            - ./composer.lock:/usr/src/composer.lock
            - ./phpstan.neon.dist:/usr/src/phpstan.neon.dist
            - ./phpunit.xml:/usr/src/phpunit.xml
            - ./public:/usr/src/public
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            update:
                condition: service_started
        extra_hosts:
            - "host.docker.internal:host-gateway"

    update:
        build:
            context: .
            dockerfile: docker/Dockerfile.php
            target: dev
            args:
                user: ${DOCKER_DEFAULT_USER:-devops}
                uid: ${DOCKER_DEFAULT_UID:-1000}
        restart: no
        command: sh -c "./update.sh"
        volumes:
            - ./composer.json:/usr/src/composer.json
            - ./composer.lock:/usr/src/composer.lock
            - ./.env:/usr/src/.env
            - ./deployment/bin/update.sh:/usr/src/update.sh
        depends_on:
            postgres:
                condition: service_healthy

    scheduler:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile.php
            target: dev_scheduler
            args:
                user: ${DOCKER_DEFAULT_USER:-devops}
                uid: ${DOCKER_DEFAULT_UID:-1000}
        volumes:
            - ./app:/usr/src/app
            - ./config:/usr/src/config
            - ./database:/usr/src/database
            - ./routes:/usr/src/routes
            - ./storage:/usr/src/storage
            - ./tests:/usr/src/tests
            - ./.env:/usr/src/.env
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            update:
                condition: service_started
        extra_hosts:
            - "host.docker.internal:host-gateway"

    worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile.php
            target: dev_worker
            args:
                user: ${DOCKER_DEFAULT_USER:-devops}
                uid: ${DOCKER_DEFAULT_UID:-1000}
        volumes:
            - ./app:/usr/src/app
            - ./config:/usr/src/config
            - ./database:/usr/src/database
            - ./routes:/usr/src/routes
            - ./storage:/usr/src/storage
            - ./tests:/usr/src/tests
            - ./.env:/usr/src/.env
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            update:
                condition: service_started
        extra_hosts:
            - "host.docker.internal:host-gateway"

    redis:
        image: redis:7.2.4-alpine
        restart: unless-stopped
        volumes:
            - devops_redis:/data
        ports:
            - "63790:6379"
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres:
        build:
            context: .
            dockerfile: docker/Dockerfile.postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            PGUSER: ${DB_USERNAME:-postgres}
            POSTGRES_DB: ${DB_DATABASE:-devops}
        volumes:
            - devops_postgres:/var/lib/postgresql/data
        ports:
            - "54320:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        build:
            context: .
            dockerfile: docker/Dockerfile.nginx
            target: dev
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            app:
                condition: service_started

    frontend:
        restart: unless-stopped
        tty: true
        build:
            context: .
            dockerfile: docker/Dockerfile.frontend
        volumes:
            - ./app:/usr/src/app
            - ./config:/usr/src/config
            - ./database:/usr/src/database
            - ./resources:/usr/src/resources
            - ./routes:/usr/src/routes
            - ./storage:/usr/src/storage
            - ./.env:/usr/src/.env
            - ./package.json:/usr/src/package.json
            - ./package-lock.json:/usr/src/package-lock.json
            - ./postcss.config.js:/usr/src/postcss.config.js
            - ./tailwind.config.js:/usr/src/tailwind.config.js
            - ./vite.config.js:/usr/src/vite.config.js
            - ./public:/usr/src/public
        ports:
            - "5173:5173"
        depends_on:
            app:
                condition: service_started
