volumes:
  storage:
  redis:
  postgres:

services:
  app:
    image: irobaka/devops-app:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/.env
      - storage:/usr/src/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      update:
        condition: service_started

  scheduler:
    image: irobaka/devops-scheduler:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/.env
      - storage:/usr/src/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      update:
        condition: service_started

  worker:
    image: irobaka/devops-worker:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/.env
      - storage:/usr/src/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      update:
        condition: service_started

  update:
    image: irobaka/devops-app:${IMAGE_TAG}
    restart: no
    command: sh -c "./update.sh"
    volumes:
      - ./.env:/usr/src/.env
      - storage:/usr/src/storage
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: irobaka/devops-nginx:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: irobaka/devops-postgres:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PGUSER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
