FROM postgres:15

RUN echo "SELECT 'CREATE DATABASE devops_test' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'devops_test')\gexec" >> /docker-entrypoint-initdb.d/10-create-testing-database.sql
