FROM node:18.20.2-alpine as assets

WORKDIR /usr/src
COPY ../package.json ../package-lock.json ./
RUN npm install
COPY .. .
RUN npm run build

FROM nginx:1.26.0-alpine as dev

COPY .. /usr/src
COPY ../deployment/config/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

FROM dev as prod

COPY --from=assets /usr/src/public/build /usr/src/public/build
