FROM node:18.20.2-alpine AS base
WORKDIR /usr/src

COPY ../package.json ../package-lock.json ./
RUN npm install

COPY .. .

FROM base AS dev
EXPOSE 5173
CMD ["npm", "run", "dev"]

FROM base AS prod
CMD ["npm", "run", "build"]

