{
 "title": "Panel dowodzenia",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Methods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(request_method) (count_over_time({job=\"fluentbit\"} | json | service_name = `nginx` | line_format `{{.log}}` | json | __error__=\"\"[$__range]))"
    }
   ]
  },
  {
   "title": "Failed  requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"fluentbit\"} | json | service_name = `nginx` | line_format `{{.log}}` | json | request_method != `OPTIONS` | status > 399"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({job=\"fluentbit\"} | json | service_name = `nginx` | line_format `{{.log}}` | json | __error__=\"\"[$__range]))"
    }
   ]
  }
 ]
}