name: 'Build PostgreSQL'
description: 'Build PostgreSQL image and push to DockerHub'
inputs:
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub access token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    - run: |
        docker build -t $POSTGRES_IMAGE -f docker/Dockerfile.postgres .
        docker push $POSTGRES_IMAGE
      shell: bash
