name: Feature branch pull request

on:
  pull_request:
    branches: ["develop"]

env:
  APP_IMAGE: irobaka/devops-app:${{ github.sha }}-demo
  SCHEDULER_IMAGE: irobaka/devops-scheduler:${{ github.sha }}-demo
  WORKER_IMAGE: irobaka/devops-worker:${{ github.sha }}-demo
  POSTGRES_IMAGE: irobaka/devops-postgres:${{ github.sha }}-demo
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build images
        run: |
          docker build -t $APP_IMAGE --target=prod --build-arg user=devops --build-arg uid=1000 -f docker/Dockerfile.php .
          docker build -t $SCHEDULER_IMAGE --target=prod_scheduler --build-arg user=devops --build-arg uid=1000 -f docker/Dockerfile.php .
          docker build -t $WORKER_IMAGE --target=prod_worker --build-arg user=devops --build-arg uid=1000 -f docker/Dockerfile.php .
          docker build -t $POSTGRES_IMAGE -f docker/Dockerfile.postgres .
      - name: Run phpstan
        run: docker run --rm -t $APP_IMAGE ./vendor/bin/phpstan analyze --memory-limit=1G
      - name: Run phpinsights
        run: docker run --rm -t $APP_IMAGE php artisan insights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90 --ansi --format=github-action
      - name: Run test
        run: |
          docker-compose -f docker-compose.ci.yml up -d
          docker-compose -f docker-compose.ci.yml exec -T app php artisan config:clear
          docker-compose -f docker-compose.ci.yml exec -T app cp .env.example .env
          docker-compose -f docker-compose.ci.yml exec -T app php artisan test
          docker-compose -f docker-compose.ci.yml down
