name: Pull request

on:
  pull_request:
    branches: ["main"]

env:
  APP_IMAGE: irobaka/devops-app:${{ github.sha }}
  SCHEDULER_IMAGE: irobaka/devops-scheduler:${{ github.sha }}
  WORKER_IMAGE: irobaka/devops-worker:${{ github.sha }}
  POSTGRES_IMAGE: irobaka/devops-postgres:${{ github.sha }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/jobs/build-app-images
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ./.github/workflows/jobs/build-postgres
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ./.github/workflows/jobs/analyze
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ./.github/workflows/jobs/test
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  remove-images:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/jobs/remove-images
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_PASSWORD }}
          image-tag: ${{ github.sha }}
