name: Devops pipeline

on:
  push:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: devops-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: cp .env.ci .env

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Compile assets
        run: |
          npm install
          npm run build

      - name: phpstan
        run: ./vendor/bin/phpstan analyse --memory-limit=1G

      - name: phpinsights
        run: |
          php artisan insights --no-interaction \
          --min-quality=90 --min-complexity=90 \
          --min-architecture=90 --min-style=90 \
          --ansi --format=github-action

      - name: Run tests
        run: php artisan test

      - name: Copy SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" >> ./id_devops
          chmod 600 id_devops

      - name: Run deploy script
        run: |
          scp -C -o StrictHostKeyChecking=no -i ./id_devops ./deployment/bin/deploy.sh ${{ secrets.SSH_CONNECTION_STAGING }}:/home/devops/deploy.sh
          scp -C -o StrictHostKeyChecking=no -i ./id_devops ./id_devops ${{ secrets.SSH_CONNECTION_STAGING }}:/home/devops/.ssh/id_devops
          ssh -tt -o StrictHostKeyChecking=no -i ./id_devops ${{ secrets.SSH_CONNECTION_STAGING }} "chown devops:devops /home/devops/deploy.sh && chmod +x /home/devops/deploy.sh"
          ssh -tt -o StrictHostKeyChecking=no -i ./id_devops ${{ secrets.SSH_CONNECTION_STAGING }} "/home/devops/deploy.sh ${{ secrets.POSTGRES_PASSWORD }}"
