name: Devops pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: devops-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: cp .env.ci .env

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
        run: npm install

      - name: Install assets
        run: npm run build

      - name: phpstan
        run: ./vendor/bin/phpstan analyse --memory-limit=1G

      - name: phpinsights
        run: |
          php artisan insights --no-interaction \
          --min-quality=90 --min-complexity=90 \
          --min-architecture=90 --min-style=90 \
          --ansi --format=github-action

      - name: Run tests
        run: php artisan test
